runners:
 local-runner:
  image: stag:5000/ubuntu-generic
  
jobs:   
 build_run_sim:
  resource_spec: micro 
  runner: local-runner
  privileged: True
  device: raspberry-pi-device1
  steps:
   - run:
      name: Connect to Pico
      command: |
       export LC_ALL=C.UTF-8
       export LANG=C.UTF-8
       export AMPY_PORT=/dev/ttyACM0
       ampy put lib
       ampy run main.py
    
workflows:
 complete-build-test:
  triggers:
   - push
  jobs:
   - build_run_sim
