runners:
 local-runner:
  image: work1-virtualbox:5000/ubuntu-generic
  
jobs:   
 build_run_sim:
  resource_spec: micro 
  runner: local-runner
  privileged: True
  steps:
   - run:
      name: Setup Environment
      command: |
       apt-get -y update
       apt-get -y install python3-pip
       pip3 install adafruit-ampy
   - run:
      name: Connect to Pico
      command: |
       export LC_ALL=C.UTF-8
       export LANG=C.UTF-8
       export AMPY_PORT=/dev/ttyACM0
       ampy put lib
       ampy run main.py
    
workflows:
 complete-build-test:
  jobs:
   - build_run_sim